default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  database: railway
  username: postgres
  password: BTW2zoRAeF2TBGga3FRn
  host: containers-us-west-176.railway.app
  port: 7573
  pool: 5 